### ISSUE TITLE
as 3.0 打的包上传 server端报index out of range

### ISSUE THREAD

**Issue by songzcn** [zhao0/ipapk-server#16]
```buffer.js:831
throw new RangeError('Index out of range');
^
RangeError: Index out of range
at checkOffset (buffer.js:831:11)
at Buffer.readUInt16LE (buffer.js:877:5)
at parseExtra (/usr/local/lib/node_modules/ipapk-server/node_modules/adm-zip/zipEntry.js:154:25)
at Object.set extra [as extra] (/usr/local/lib/node_modules/ipapk-server/node_modules/adm-zip/zipEntry.js:209:13)
at readEntries (/usr/local/lib/node_modules/ipapk-server/node_modules/adm-zip/zipFile.js:40:29)
at readMainHeader (/usr/local/lib/node_modules/ipapk-server/node_modules/adm-zip/zipFile.js:72:9)
at new module.exports (/usr/local/lib/node_modules/ipapk-server/node_modules/adm-zip/zipFile.js:18:9)
at new module.exports (/usr/local/lib/node_modules/ipapk-server/node_modules/adm-zip/adm-zip.js:17:20)
at /usr/local/lib/node_modules/ipapk-server/ipapk-server.js:391:17
at parseOutput (/usr/local/lib/node_modules/ipapk-server/node_modules/apk-parser3/lib/index.js:42:10)
```

**Comment by songzcn** [comment]
去adm-zip repo上查了这个问题，发觉大家都说版本从0.4.7回退到0.4.6及以前就好了
