### ISSUE TITLE
ubuntu16.04下安装成功后，执行ipapk-server报错

### ISSUE THREAD

**Issue by songzcn** [zhao0/ipapk-server#2]
module.js:328
    throw err;
    ^

Error: Cannot find module 'Guid'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ipapk-server/ipapk-server.js:18:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by zhao0** [comment]
好的，我会看一下

**Comment by zhao0** [comment]
0.1.6版本已经修复，Ubuntu 64位安装请参考Readme

**Comment by zhao0** [comment]
另外，项目web页面还没有完成

**Comment by songzcn** [comment]
赞，另外在mac上安装成功后执行，generate-certificate.sh的路径也有问题，sh: /Users/xxx/Downloads/generate-certificate.sh: No such file or directory

**Comment by zhao0** [comment]
这块我已经改过了，你再试试

**Comment by songzcn** [comment]
mac下也可以了

**Comment by zhao0** [comment]
web下载页面正在搞，再等几天

**Comment by songzcn** [comment]
好的，👍
