### ISSUE TITLE
上传包的时候有bug

### ISSUE THREAD

**Issue by panjiulong** [zhao0/ipapk-server#26]
pngdefry : seen 1 file(s), wrote 1 file(s)
/usr/local/lib/node_modules/ipapk-server/ipapk-server.js:302
      var data = info[0];
                     ^

TypeError: Cannot read property '0' of undefined
    at /usr/local/lib/node_modules/ipapk-server/ipapk-server.js:302:22
    at f (/usr/local/lib/node_modules/ipapk-server/node_modules/once/once.js:25:25)
    at ZipFile.<anonymous> (/usr/local/lib/node_modules/ipapk-server/node_modules/ipa-extract-info/index.js:52:33)
    at emitNone (events.js:106:13)
    at ZipFile.emit (events.js:208:7)
    at Immediate._onImmediate (/usr/local/lib/node_modules/ipapk-server/node_modules/yauzl/index.js:246:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by wanyakun** [comment]
+1  企业证书adhoc的最近出现这个问题了，以前挺好的

**Comment by wanyakun** [comment]
@panjiulong extract info时的问题，没有获取到信息， ipa-extract-info 更新到最新的就可以了

**Comment by wanyakun** [comment]
@zhao0 好，改天提一个
