### ISSUE TITLE
curl 上传文件报错

### ISSUE THREAD

**Issue by red3** [zhao0/ipapk-server#5]
curl 上传文件后报错：

```
.nvm/versions/node/v5.6.0/lib/node_modules/ipapk-server/ipapk-server.js:209
      var obj = files.package[0];
                             ^
TypeError: Cannot read property '0' of undefined
    at /Users/herui/.nvm/versions/node/v5.6.0/lib/node_modules/ipapk-server/ipapk-server.js:209:30
    at /Users/herui/.nvm/versions/node/v5.6.0/lib/node_modules/ipapk-server/node_modules/multiparty/index.js:129:9
    at /Users/herui/.nvm/versions/node/v5.6.0/lib/node_modules/ipapk-server/node_modules/multiparty/index.js:108:9
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

安装的时候，有个依赖好像缺失了，报警告了：
> npm WARN browserify-shim@3.8.12 requires a peer of browserify@>= 2.3.0 < 14 but none was installed.

**Comment by zhao0** [comment]
麻烦贴一下你的curl命令

**Comment by red3** [comment]
sorry, 应该是我的锅，仔细检查了，发现有拼写错误，我关 issue 吧.

**Comment by zhao0** [comment]
恩，我下次加点error处理

**Comment by red3** [comment]
sorry, 又麻烦你了☺️

我检查拼写错误后，发起了 curl：
```
curl 'https://10.1.33.108:1234/upload' -F "package=@/Users/herui/Desktop/1.ipa" -F "changelog=test" --insecure
```
等待很长时间后会报错误：
```
curl: (56) SSLRead() return error -9806
```

我怀疑文件没有上传成功，但是，当我新建一个空白 ipa 文件上传的时候，发现会执行到 parseIpa 函数里面，进而报错，说明文件上传是没有问题，是解析过程有问题？

**Comment by zhao0** [comment]
服务端那边有什么输出吗

**Comment by red3** [comment]
没有，很奇怪

**Comment by zhao0** [comment]
怀疑是你的ipa里面没有`AppIcon60x60@3x.png`这个文件

**Comment by red3** [comment]
确实是没有这个，我刚才在怀疑这个，因为我在用 ipa-server 这个项目的时候当时页面没有显示ipa 的 icon，发现项目默认读的是 3x 图。

这个为什么引起这个错误了？

**Comment by zhao0** [comment]
这是一个bug，遍历没有找到这个文件后没有把这个promise给reject

**Comment by zhao0** [comment]
是不是普遍用2x图

**Comment by red3** [comment]
应该再尝试找下 2x，2x肯定有，要不然苹果也不给过

**Comment by zhao0** [comment]
好的

**Comment by zhao0** [comment]
我改了一些，你可以升级一下

**Comment by red3** [comment]
好的
