### ISSUE TITLE
macOS 无法启动 ipapk-server

### ISSUE THREAD

**Issue by CharlesQiu** [zhao0/ipapk-server#9]
macOS Sierra 10.12.3 安装后进入含有ipa包的文件夹运行

```
ipapk-server
```

出现如下错误

```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/usr/local/lib/node_modules/ipapk-server/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	/usr/local/lib/node_modules/ipapk-server/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1609728 which is past end of file 152064
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ipapk-server/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by zhao0** [comment]
看报错信息，应该是sqllite没安装成功，你可以尝试卸载ipapk-server后重装

**Comment by CharlesQiu** [comment]
安装了 sqlite3 依然报错
```
╰─➤  sqlite3 --version                                                                       
3.14.0 
```

安装时有个警告
```
╰─➤  sudo npm install ipapk-server
/usr/local/bin/ipapk-server -> /usr/local/lib/node_modules/ipapk-server/ipapk-server.js
/usr/local/lib
└── ipapk-server@0.2.5

npm WARN browserify-shim@3.8.13 requires a peer of browserify@>= 2.3 but none was installed.
```
难道 browserify 版本太高？
```
╰─➤  browserify --version
14.1.0
```

**Comment by SimleCp** [comment]
我也碰到了你这个问题. 安装了最新版的node.js也不行.

**Comment by SimleCp** [comment]
把npm的源改成淘宝源  然后使用淘宝的cnpm安装  就可以了. 如果是系统版本比较高的macOS 记得sudo提权

**Comment by zhao0** [comment]
@SimleCp Good!
